services:
  - type: web
    name: my-python-app
    env: python
    plan: free  # bisa diganti sesuai kebutuhan
    region: oregon
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn backend.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PIP_NO_BUILD_ISOLATION
        value: "0"
      - key: PIP_DEFAULT_TIMEOUT
        value: "100"
    pythonVersion: "3.11"
